url: 'https://thestyleloungelichfield.com'

# Enable CloudCannon UI
cloudcannon:
  data: true

# Sass partials directory
sass:
  sass_dir: _sass
  style: compressed

uploads_dir: /assets/images

# Global permalinks
permalink: /:path

# Collections configurations
# collections:
#   my_collection:
#     output: true
#     permalink: /:title

# Defaults
defaults:
  -
    scope:
      path: "/posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: blog
      title:
      subtitle:
      author:
      description: SEO content. Limit to 160 characters.
      preview_image:
      preview_image_alt_text:
      categories: []
      tags: []
      keywords: []
      sections:
  -
    scope:
      path: "/drafts" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: blog
      title:
      subtitle:
      author:
      description: SEO content. Limit to 160 characters.
      preview_image:
      preview_image_alt_text:
      categories: []
      tags: []
      keywords: []
      sections:

# Sections (Page blocks)
sections: []
_array_structures:
  sections:
    - label: Two Image Grid
      description: A responsive 2-column grid with image, heading and paragraph
      icon: grid_on
      value:
        _id: 2-image-grid
        label: Two Image Grid
        rows:
          - background_class:
            heading:
            content_text:
            image:
            alt_text:
            add_button:
            button_text:
            button_url:
    - label: 'Column Section #1'
      description: 2 column section with image, heading and paragraph
      icon: vertical_split
      value:
        _id: column-section-1
        label: 'Column Section #1'
        background_class:
        heading:
        content_html:
        image:
        alt_text:
        add_button: false
        button_text:
        button_url:
    - label: Three Image Gallery
      description: A responsive 3-image gallery with large and small images
      icon: view_carousel
      value:
        _id: 3-image-gallery
        label: Three Image Gallery
        gallery_large_image:
        gallery_large_image_alt_text:
        gallery_box_1_image:
        gallery_box_1_image_alt_text:
        gallery_box_2_image:
        gallery_box_2_image_alt_text:
    - label: Highlight Boxes
      description: Highlight boxes with hover-over effect
      icon: view_column
      value:
        _id: highlight-boxes
        label: Highlight Boxes
        background_class:
        highlights:
          - heading:
            highlight_image:
            highlight_image_alt_text:
            url:
    - label: Team Overview
      description: A section to present team members
      icon: account_box
      value:
        _id: team
        label: Team Overview
        background_class:
        button_url:
        team_members:
          - name:
            role:
            bio_text:
            avatar_image:
    - label: Professionals
      description: A section featuring the professionals and their services
      icon: people
      value:
        _id: professionals
        label: Professionals
        background_class:
        professionals:
          - name:
            bio_text_html:
            profile_image:
    - label: Services
      description: A section featuring the services offered and CTA buttons
      icon: library_books
      value:
        _id: professionals
        label: Professionals
        background_class:
        services:
          - name:
            description_text_html:
            feature_image:
            alt_text:
    - label: 'Call-to-Action #1'
      description: A call-to-action section with background image
      icon: card_membership
      value:
        _id: cta-1
        label: Call-to-Action
        background_image:
        button_url:
    - label: Ads Slider
      description: A simple slider allowing for multiple promo banners. Update the content via Elfsight.
      icon: calendar_view
      value:
        _id: ads-slider
        label: Ads Slider
        background_class:      
    - label: Testimonials Slider
      description: A simple slider featuring Facebook Reviews. Automatically updated.
      icon: grade
      value:
        _id: testimonial-slider
        label: Testimonials Slider
        background_class:
    - label: Contact from
      description: A simple contact form for client submissions
      icon: horizontal_split
      value:
        _id: contact-form
        label: Contact Form
        background_class:
        action_code_block:
        method: post
    - label: Horizontal Divider
      description: A horizontal line to divide sections
      icon: maximize
      value:
        _id: dividers
        label: Dividers
        size:
    - label: Instagram Feed
      description: A section with the Instagram Feed
      icon: image
      value:
        _id: instagram-feed
        label: Instagram Feed
        background_class:

# Plugins installed
plugins:
  - jekyll-sitemap
  - jekyll_picture_tag
  
# configuration of jekyll_picture_tag plugin
picture:
  source: "/"
  output: "generated/"
  suppress_warnings: true

# Configuration for the WebP Generator Plugin
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/", "assets/images", "/assets/images/srcset"]
  nested: true
  regenerate: false

# Configuration of the compress_html layout
compress_html:
  comments: all # Removes all comments; remove this line to enable comments in production site

# Background classes for the sections
background_classes:
  - bg-primary
  - bg-secondary
  - bg-accent
  - bg-reset

methods:
  - get
  - post

sizes:
  - Small
  - Medium
  - Large  

_comments:
  background_class: Choose from the pre-determined background classes for the section. Defaults to site's body background color
  description: Optimize this content for SEO. Provide valuable information about the page in less than 160 characters
  preview_image: Preview image for social sharing. If left blank, it will use the image defined in the 'Settings' file under the 'Basics' menu
  header_image: Image for the page's header banner
  main_image: Image for the page's header banner
  alt_text: Important for SEO; put a description of the image with keywords
  main_image_alt_text: Important for SEO; put a description of the image with keywords
  image_alt_text: Important for SEO; put a description of the image with keywords
  highlight_image_alt_text: Important for SEO; put a description of the image with keywords
  button_url: The destination path for the button click action