basics:
  site_title: The Style Lounge
  description: Hair salon and beauty treatments in Lichfield
  site_base_url: 'https://thestyleloungelichfield.com'
  site_logo_image: assets/images/the-style-lounge-logo.png
  site_thumb_image: assets/images/hair-salon-lichfield-the-style-lounge-oribe-1.jpg
  contact_email: sales@thestyleloungelichfield.com
  phone_number: +44 1543 897790
  address: '5-7 Greenhill, Lichfield'
opening_hours:
  monday: 10am-5pm
  tuesday: 10am-5pm
  wednesday: 10am-5pm
  thursday: 10am-5pm
  friday: 9am-4pm
  saturday: 11am-3pm
  sunday: closed
social:
  facebook_url: 'https://facebook.com/thestyleloungelich'
  instagram_url: 'https://instagram.com/thestyleloungelichfield'
  instagram_handle: '@thestyleloungelichfield'
navigation:
  - name: services
    url: /services
    button: false
  - name: Our Team
    url: /team
    button: false
  - name: Shop
    url: 'https://shop.thestyleloungelichfield.com'
    button: false
  - name: Contact
    url: /contact
    button: false
  - name: Make Appointment
    url: >-
      https://www.premiersoftware.co.uk/Book-OnlineV2/?i=1390ac4e2ce6e6d2f47d573ab30aa42a
    button: true
logos:
  navbar_logo_image: /assets/logos/your-logo.png
  footer_logo_image: /assets/logos/your-logo-alternative.png
colors:
  dark_color: '#231f20'
  light_color: '#eaeaea'
  accent_color: '#ad974f'
  accent_shade_color: '#8e793e'
fonts:
  fonts_code_block: >-
    <link
    href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;300;400&family=Quicksand:wght@300;400;600&display=swap"
    rel="stylesheet">
  body_font_family: '''Quicksand'', sans-serif;'
  design_font_family: '''Josefin Sans'', sans-serif;'
seo:
  fb_app_id: 123456789
  keywords:
    - hair salon
    - lichfield
    - optimization
  description: Looking for a hair salon in Lichfield
configuration:
  google_tag_manager_code_block: >-
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new
    Date().getTime(),event:'gtm.js'});var
    f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5TZCS67');</script>
  google_analytics_code_block:
  form_submission_handler_code_block: "https://thestyleloungelichfield.us2.list-manage.com/subscribe/post"
  flexbox_framework_code_block: >-
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">